services:
  db-mock-tests:
    container_name: db-mock-tests
    build:
      context: .
      dockerfile: ./tests/Dockerfile-mock-db
    environment:
      - POSTGRES_USER=mock
      - POSTGRES_PASSWORD=mock
      - POSTGRES_DB=mock
    ports:
      - 5435:5432
  mock-db:
    container_name: mock-db
    build:
      context: .
      dockerfile: ./tests/Dockerfile-db
    environment:
      - POSTGRES_USER=mock
      - POSTGRES_PASSWORD=mock
      - POSTGRES_DB=db
    ports:
      - 5433:5432