services:
  mock-db:
    container_name: mock-db
    build:
      context: .
      dockerfile: Dockerfile-mock-db
    environment:
      - POSTGRES_USER=mock
      - POSTGRES_PASSWORD=mock
      - POSTGRES_DB=db
    ports:
      - 5433:5432
